### ISSUE TITLE
Feature request: add card colours to message log

### ISSUE THREAD

**Issue by hrudham** [marlanperumal/codenames-frontend#3]
Please name the colour of the cards clicked on in the message log. For bonus points, add an icon, or colour the text to reflect this too.

**Comment by aquavitae** [comment]
If the intent is to be able to see more easily who has clicked what, how about adding some info to the card after it's clicked. Something like this:
![image](https://user-images.githubusercontent.com/5753990/84419609-2699e080-ac19-11ea-9ce2-b64490ded32e.png)

* Keep the word text visible
* Make the red background softer so that there's less contrast with the text
* Add the name of the player who clicked the card
* Change the border to the player's colour, in this case Blue, to indicate that it was an incorrect pick.

**Comment by marlanperumal** [comment]
I'm actually not keen on adding functionality like this and keeping the interface as simple as possible. The one way this might work if there was a view mode toggle for Simple/Advanced and then put all of these types of changes behind the Advanced view

**Comment by marlanperumal** [comment]
Adding colours of Player and Card to the Message Log does make sense though

**Comment by aquavitae** [comment]
I don't really find the log useful - too much text. I have to say I also don't really care who clicked on a card, but I do often want to know what the word was afterwards. So to revise my suggestion: do away with the logs, and keep the text once the card is flipped. To keep it looking simpler it could ever just be a hover effect.

**Comment by marlanperumal** [comment]
onHover might work well actually

**Comment by aquavitae** [comment]
That should be easy to do then. I might look at it this weekend if I get time

**Comment by marlanperumal** [comment]
I believe the desired outcome has been achieved in #11. If there's still a need to colour the logs then please reopen.
